CREATE TABLE comment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    content VARCHAR(255) DEFAULT NULL,
    ticketId INTEGER DEFAULT NULL,
    buyername VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (ticketId) REFERENCES ticket(id) 
);
